"""Records in, markdown out. Nothing ever parses the markdown back.

The documents this renders are the ones agents actually read, and they are worth
generating well. But they are **views**. The moment a view is also an input, the
system has two encodings of one fact, and the source harness spent a dozen debt
entries paying for that (see `entries.py`).

So `check()` asserts every view on disk is byte-identical to what the records
render. A hand-edit is a validation failure with the diff named, not a silent
divergence discovered four hours later (H72, H140).

Two conventions are inherited verbatim from the source harness's board, because
they were already right:

* **Reuse the reader that owns the parse.** Here there is one reader -- the
  entry store -- and every view is a projection of it.
* **Every section reports how many things it read.** A board that says "no live
  claims" must not be indistinguishable from a board that read nothing
  (H81, H96). Every section below prints its count, including zero.
"""
from __future__ import annotations

import pathlib

BANNER = ("<!-- GENERATED by `ar render` from state/entries/. Do not edit: your "
          "change will be overwritten and `ar validate` will fail first. Edit "
          "the entry record instead. -->")

MEMOS_INDEX = "INDEX.md"


def _memos_pending(config) -> bool:
    """True when the memos directory holds anything worth indexing. A domain
    with no memos gets no index view at all: rendering an empty directory into
    every fresh domain would make adoption a validation failure (see
    `check_views`' migrate distinction for the same reasoning)."""
    memos = config.paths.memos
    if not memos.is_dir():
        return False
    index = memos / MEMOS_INDEX
    return any(p.is_file() and p != index for p in memos.iterdir())


def memos_index_view(config, entries) -> str:
    """The memos directory at a glance: which memo carries which entry's
    evidence. A projection of the entry store plus one directory listing --
    nothing parses the markdown back. The index excludes itself, so the view
    is stable across renders."""
    memos = config.paths.memos
    index = memos / MEMOS_INDEX
    names = sorted(p.name for p in memos.iterdir()
                   if p.is_file() and p != index)

    cited: dict[str, list[str]] = {name: [] for name in names}
    prefix = f"{memos.name}/"
    for e in entries:
        refs = []
        if e.result is not None and e.result.memo:
            refs.append(e.result.memo)
        for source in e.sources or []:
            # A source line may cite several paths separated by ';' or spaces.
            refs.extend(source.replace(";", " ").split())
        seen = set()
        for ref in refs:
            name = ref[len(prefix):] if ref.startswith(prefix) \
                else ref.rsplit("/", 1)[-1]
            if name in cited and name not in seen:
                seen.add(name)
                cited[name].append(f"{e.id} ({e.status})")

    cited_names = [n for n in names if cited[n]]
    uncited = [n for n in names if not cited[n]]
    out = [BANNER, "", f"# Memos — {memos.name}", "",
           "> Prose findings and evidence records; every closed entry's pointer",
           "> lands here. Rendered from the entry records: edit the record,",
           "> then re-run `ar render` — never this file.", "",
           f"**{len(names)} files read: {len(cited_names)} cited by an entry, "
           f"{len(uncited)} not referenced by any entry.**", ""]
    out += [f"## Cited by an entry ({len(cited_names)})"]
    if cited_names:
        out += ["", "| Memo | Entries |", "|---|---|"]
        for n in cited_names:
            out.append(f"| `{n}` | {', '.join(cited[n])} |")
    else:
        out += ["", "_No memo is referenced by an entry record yet._"]
    out += ["", f"## Not referenced by any entry ({len(uncited)})"]
    if uncited:
        out += [""] + [f"- `{n}`" for n in uncited]
    else:
        out += ["", "_Every memo is referenced._"]
    return "\n".join(out) + "\n"


def _fmt(value, width=None):
    if isinstance(value, float):
        text = f"{value:,.4g}"
    elif isinstance(value, int):
        text = f"{value:,}"
    else:
        text = str(value)
    return text.ljust(width) if width else text


def queue_view(track, entries, machine=None) -> str:
    """One track's queue: a Closed table of pointers, then the open entries."""
    machine = machine or track.machine
    mine = [e for e in entries if track.is_id(e.id)]
    closed = [e for e in mine if machine.status(e.status).terminal]
    open_ = [e for e in mine if not machine.status(e.status).terminal]

    out = [BANNER, "", f"# {track.title}", ""]
    if track.description:
        out += [f"> {track.description}", ""]
    out += [
        f"Statuses: {' | '.join(sorted(machine.statuses))}. "
        f"Initial: `{machine.initial}`.",
        "",
        f"**{len(mine)} entries read: {len(open_)} open, {len(closed)} closed.**",
        "",
        "Agents do not edit this file; it is rendered from the entry records. "
        "Use `ar claim`, `ar close`, `ar entry`.",
        "",
    ]

    out += ["## Closed", "",
            f"One row per terminal entry ({len(closed)}). Pointers only: the "
            "reasoning lives in the memo.", ""]
    if closed:
        out += ["| Entry | Status | Kind | Disposition | Applicability | Readiness | Date | Evidence | Verdict |",
                "|---|---|---|---|---|---|---|---|---|"]
        for e in sorted(closed, key=lambda e: e.number):
            r = e.result
            out.append(
                f"| {e.id} | {e.status} | {(r.closure_kind if r else '') or '—'} "
                f"| {r.disposition if r else '—'} "
                f"| {r.applicability.describe() if r and r.applicability else 'unscoped (legacy)'} "
                f"| {e.gate_readiness(machine.required_gates)} "
                f"| {(r.at[:10] if r else '')} | `{r.memo if r else ''}` "
                f"| {((r.summary if r else '') or '—').splitlines()[0][:120]} |")
    else:
        out.append("_No closed entries._")
    out.append("")

    out += ["## Open", "", f"{len(open_)} entry/entries.", ""]
    for e in sorted(open_, key=lambda e: e.number):
        out += _entry_section(e, machine.required_gates)
    if not open_:
        out.append("_No open entries._")
    return "\n".join(out).rstrip() + "\n"


def _entry_section(e, required_gates=()) -> list[str]:
    out = [f"### {e.id} — {e.title}", ""]
    rows = [("Status", e.status), ("Readiness", e.gate_readiness(required_gates)),
            ("Context", e.context.describe())]
    if e.claim:
        budget = ", ".join(filter(None, [
            e.claim.budget,
            f"max {e.claim.max_runs} runs" if e.claim.max_runs else "",
            f"max {e.claim.max_hours} h" if e.claim.max_hours else ""]))
        rows.append(("Claimed", f"{e.claim.session} · {e.claim.at[:16]}"
                                + (f" · budget: {budget}" if budget else "")))
    rows += [("Confidence", f"{e.confidence:.2f}"),
             ("Impact", f"{e.impact:.4g}"),
             ("Cost", f"{e.cost:.4g} run-units")]
    if e.gate:
        rows.append(("Gate", e.gate))
    if e.mechanisms:
        rows.append(("Mechanisms", ", ".join(f"`{m}`" for m in e.mechanisms)))
    if e.tags:
        rows.append(("Tags", ", ".join(f"`{t}`" for t in e.tags)))
    for label, value in rows:
        out.append(f"- **{label}:** {value}")
    for gate in e.gates:
        out.append(f"- **Acceptance {gate.name}:** {gate.state} "
                   f"({'required' if gate.required else 'optional'})"
                   + (" — " + "; ".join(gate.evidence) if gate.evidence else ""))
    for label, value in (("Hypothesis", e.hypothesis), ("Prediction", e.prediction),
                         ("Bar", e.bar), ("Why filed", e.why_filed)):
        if value:
            out.append(f"- **{label}:** {value}")
    if e.null_checks:
        out.append("- **Null checks:** " + "; ".join(e.null_checks))
    for label, values in (("Sources", e.sources), ("Supersedes", e.supersedes),
                          ("Related", e.related)):
        if values:
            out.append(f"- **{label}:** " + ", ".join(values))
    if e.body:
        out += ["", e.body.rstrip()]
    out.append("")
    return out


def board(config, entries, runs, target=None, best=None, skipped_runs=0,
          best_metrics=None) -> str:
    """One screen answering what is currently true.

    Modelled on the source harness's `bin/board`, which existed because a cold
    session had to read ~8,000 lines of append-only prose to find out who was
    working on what (H108). Here it is a projection of records, so it cannot
    disagree with them.
    """
    goal = config.goal
    out = [f"# {config.name} — board", ""]

    out.append(f"## Goal: {goal.id}")
    out.append(f"objective  {goal.objective}  ({goal.direction})")
    if goal.derived:
        out.append("derived    " + ", ".join(f"{k} = {v}" for k, v in goal.derived.items()))
    out.append(f"target     {_fmt(target) if target is not None else '(not probed)'}"
               + ("  [moving]" if goal.target.moving else ""))
    if best is not None and target:
        value, entry_id = best
        distance = goal.distance_to(value, target)
        # GOAL MET is the stop decision's own answer: a stop_when clause is
        # the goal's definition of "met" (qsb requires +1% over a moving
        # target), so the board must not derive a second, looser one from
        # raw distance.
        met = goal.is_met(best_metrics or {}, target)
        out.append(f"best       {_fmt(value)}  ({entry_id})   "
                   f"distance {distance:+.2%}"
                   + ("  ** GOAL MET **" if met else ""))
    else:
        out.append("best       (no valid measurement yet)")
    out.append("")

    for track in config.tracks.values():
        mine = [e for e in entries if track.is_id(e.id)]
        machine = track.machine
        counts = {}
        for e in mine:
            counts[e.status] = counts.get(e.status, 0) + 1
        out.append(f"## {track.title} — {len(mine)} entries read")
        out.append("  " + ("  ".join(f"{k}:{v}" for k, v in sorted(counts.items()))
                           or "(none)"))
        readiness = {}
        for e in mine:
            value = e.gate_readiness(machine.required_gates)
            readiness[value] = readiness.get(value, 0) + 1
        out.append("  readiness: " + ("  ".join(
            f"{key}:{value}" for key, value in sorted(readiness.items())) or "(none)"))
        held = [e for e in mine if e.claim and not machine.status(e.status).terminal]
        out.append(f"  live claims: {len(held)}")
        for e in held:
            out.append(f"    {e.id}  {e.claim.session}  since {e.claim.at[:16]} "
                       f" [{e.gate_readiness(machine.required_gates)}]")
        queued = sorted((e for e in mine if e.status == machine.initial),
                        key=lambda e: -getattr(e, "_score", 0))
        out.append(f"  queued heads ({len(queued)} queued):")
        for e in queued[:3]:
            out.append(f"    {e.id}  {e.title[:80]} "
                       f" [{e.gate_readiness(machine.required_gates)}]")
        if not queued:
            out.append("    (none — the queue is empty, not merely all held)")
        out.append("")

    ok = [r for r in runs if r.status == "ok"]
    out.append(f"## Measurements — {len(runs)} rows read, {len(ok)} valid"
               + (f", {skipped_runs} foreign rows skipped (pre-adoption schema)"
                  if skipped_runs else ""))
    for r in sorted(runs, key=lambda r: r.started)[-3:]:
        metrics = " ".join(f"{k}={_fmt(v)}" for k, v in sorted(r.metrics.items()))
        out.append(f"  {r.id}  {r.status:8} {r.entry or '—':6} {metrics}")
    if not runs:
        out.append("  (no measurements recorded)")
    return "\n".join(out) + "\n"


# -- writing and checking views ------------------------------------------

def write_views(config, entries) -> list[pathlib.Path]:
    written = []
    for track in config.tracks.values():
        path = config.paths.root / track.view
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(queue_view(track, entries))
        written.append(path)
    if _memos_pending(config):
        path = config.paths.memos / MEMOS_INDEX
        path.write_text(memos_index_view(config, entries))
        written.append(path)
    return written


def check_views(config, entries) -> list[str]:
    """Views that differ from what the records render.

    This is invariant 1 made enforceable: a generated document that someone
    hand-edited is a build failure, not a divergence nobody notices.
    """
    problems = []
    for track in config.tracks.values():
        path = config.paths.root / track.view
        expected = queue_view(track, entries)
        if not path.exists():
            # Distinguish "you have not adopted this domain yet" from "you
            # forgot to re-render". Both leave no file, and pointing the first
            # case at `ar render` sends the reader the wrong way: rendering an
            # empty store writes an empty queue and looks like it worked.
            mine = [e for e in entries if track.is_id(e.id)]
            if not mine and track.migrate_from:
                problems.append(
                    f"{track.view} does not exist and this track holds no "
                    f"records. Its source document is {track.migrate_from!r}: "
                    f"run `ar migrate` first, then `ar render`.")
            else:
                problems.append(
                    f"{track.view} has never been rendered (`ar render`)")
        elif path.read_text() != expected:
            problems.append(
                f"{track.view} differs from what the records render. It is a "
                f"generated view: edit the entry record and re-run `ar render`.")
    if _memos_pending(config):
        path = config.paths.memos / MEMOS_INDEX
        # Message names the file relative to the domain root, matching how the
        # track problems above name their views.
        name = str(path.relative_to(config.paths.root))
        expected = memos_index_view(config, entries)
        if not path.exists():
            problems.append(f"{name} has never been rendered (`ar render`)")
        elif path.read_text() != expected:
            problems.append(
                f"{name} differs from what the records render. It is a "
                f"generated view: edit the entry record and re-run `ar render`.")
    return problems
