"""Records in, markdown out. Nothing ever parses the markdown back.

The documents this renders are the ones agents actually read, and they are worth
generating well. But they are **views**. The moment a view is also an input, the
system has two encodings of one fact, and the source harness spent a dozen debt
entries paying for that (see `entries.py`).

So `check()` asserts every view on disk is byte-identical to what the records
render. A hand-edit is a validation failure with the diff named, not a silent
divergence discovered four hours later (H72, H140).

Two conventions are inherited verbatim from the source harness's board, because
they were already right:

* **Reuse the reader that owns the parse.** Here there is one reader -- the
  entry store -- and every view is a projection of it.
* **Every section reports how many things it read.** A board that says "no live
  claims" must not be indistinguishable from a board that read nothing
  (H81, H96). Every section below prints its count, including zero.
"""
from __future__ import annotations

import html
import json
import pathlib
import re

from . import skills as skills_mod

BANNER = ("<!-- GENERATED by `ar render` from state/entries/. Do not edit: your "
          "change will be overwritten and `ar validate` will fail first. Edit "
          "the entry record instead. -->")

MEMOS_INDEX = "INDEX.md"


def _memos_pending(config) -> bool:
    """True when the memos directory holds anything worth indexing. A domain
    with no memos gets no index view at all: rendering an empty directory into
    every fresh domain would make adoption a validation failure (see
    `check_views`' migrate distinction for the same reasoning)."""
    memos = config.paths.memos
    if not memos.is_dir():
        return False
    index = memos / MEMOS_INDEX
    return any(p.is_file() and p != index for p in memos.iterdir())


def memos_index_view(config, entries) -> str:
    """The memos directory at a glance: which memo carries which entry's
    evidence. A projection of the entry store plus one directory listing --
    nothing parses the markdown back. The index excludes itself, so the view
    is stable across renders."""
    memos = config.paths.memos
    index = memos / MEMOS_INDEX
    names = sorted(p.name for p in memos.iterdir()
                   if p.is_file() and p != index)

    cited: dict[str, list[str]] = {name: [] for name in names}
    prefix = f"{memos.name}/"
    for e in entries:
        refs = []
        if e.result is not None and e.result.memo:
            refs.append(e.result.memo)
        for source in e.sources or []:
            # A source line may cite several paths separated by ';' or spaces.
            refs.extend(source.replace(";", " ").split())
        seen = set()
        for ref in refs:
            name = ref[len(prefix):] if ref.startswith(prefix) \
                else ref.rsplit("/", 1)[-1]
            if name in cited and name not in seen:
                seen.add(name)
                cited[name].append(f"{e.id} ({e.status})")

    cited_names = [n for n in names if cited[n]]
    uncited = [n for n in names if not cited[n]]
    out = [BANNER, "", f"# Memos — {memos.name}", "",
           "> Prose findings and evidence records; every closed entry's pointer",
           "> lands here. Rendered from the entry records: edit the record,",
           "> then re-run `ar render` — never this file.", "",
           f"**{len(names)} files read: {len(cited_names)} cited by an entry, "
           f"{len(uncited)} not referenced by any entry.**", ""]
    out += [f"## Cited by an entry ({len(cited_names)})"]
    if cited_names:
        out += ["", "| Memo | Entries |", "|---|---|"]
        for n in cited_names:
            out.append(f"| `{n}` | {', '.join(cited[n])} |")
    else:
        out += ["", "_No memo is referenced by an entry record yet._"]
    out += ["", f"## Not referenced by any entry ({len(uncited)})"]
    if uncited:
        out += [""] + [f"- `{n}`" for n in uncited]
    else:
        out += ["", "_Every memo is referenced._"]
    return "\n".join(out) + "\n"


def _fmt(value, width=None):
    if isinstance(value, float):
        # `,.4g` is the house format: sub-1 values keep their digits where
        # `,.0f` rounded a 0.701 objective to "1" (H2). But `g` goes
        # scientific -- 9999.99 reads "1e+04", a 6,000,000 target "6e+06" --
        # so any magnitude at or above 1 that formats scientific falls back
        # to `,.0f`. Tiny values keep the compact `1.23e-05` form.
        text = f"{value:,.4g}"
        if "e" in text and abs(value) >= 1:
            text = f"{value:,.0f}"
    elif isinstance(value, int):
        text = f"{value:,}"
    else:
        text = str(value)
    return text.ljust(width) if width else text


def queue_view(track, entries, machine=None) -> str:
    """One track's queue: a Closed table of pointers, then the open entries."""
    machine = machine or track.machine
    mine = [e for e in entries if track.is_id(e.id)]
    closed = [e for e in mine if machine.status(e.status).terminal]
    open_ = [e for e in mine if not machine.status(e.status).terminal]

    out = [BANNER, "", f"# {track.title}", ""]
    if track.description:
        out += [f"> {track.description}", ""]
    out += [
        f"Statuses: {' | '.join(sorted(machine.statuses))}. "
        f"Initial: `{machine.initial}`.",
        "",
        f"**{len(mine)} entries read: {len(open_)} open, {len(closed)} closed.**",
        "",
        "Agents do not edit this file; it is rendered from the entry records. "
        "Use `ar claim`, `ar close`, `ar entry`.",
        "",
    ]

    out += ["## Closed", "",
            f"One row per terminal entry ({len(closed)}). Pointers only: the "
            "reasoning lives in the memo.", ""]
    if closed:
        out += ["| Entry | Status | Kind | Disposition | Applicability | Readiness | Date | Evidence | Verdict |",
                "|---|---|---|---|---|---|---|---|---|"]
        for e in sorted(closed, key=lambda e: e.number):
            r = e.result
            out.append(
                f"| {e.id} | {e.status} | {(r.closure_kind if r else '') or '—'} "
                f"| {r.disposition if r else '—'} "
                f"| {r.applicability.describe() if r and r.applicability else 'unscoped (legacy)'} "
                f"| {e.gate_readiness(machine.required_gates)} "
                f"| {(r.at[:10] if r else '')} | `{r.memo if r else ''}` "
                f"| {((r.summary if r else '') or '—').splitlines()[0][:120]} |")
    else:
        out.append("_No closed entries._")
    out.append("")

    out += ["## Open", "", f"{len(open_)} entry/entries.", ""]
    for e in sorted(open_, key=lambda e: e.number):
        out += _entry_section(e, machine.required_gates)
    if not open_:
        out.append("_No open entries._")
    return "\n".join(out).rstrip() + "\n"


def _entry_section(e, required_gates=()) -> list[str]:
    out = [f"### {e.id} — {e.title}", ""]
    rows = [("Status", e.status), ("Readiness", e.gate_readiness(required_gates)),
            ("Context", e.context.describe())]
    if e.claim:
        budget = ", ".join(filter(None, [
            e.claim.budget,
            f"max {e.claim.max_runs} runs" if e.claim.max_runs else "",
            f"max {e.claim.max_hours} h" if e.claim.max_hours else ""]))
        rows.append(("Claimed", f"{e.claim.session} · {e.claim.at[:16]}"
                                + (f" · budget: {budget}" if budget else "")))
    rows += [("Confidence", f"{e.confidence:.2f}"),
             ("Impact", f"{e.impact:.4g}"),
             ("Cost", f"{e.cost:.4g} run-units")]
    if e.gate:
        rows.append(("Gate", e.gate))
    if e.mechanisms:
        rows.append(("Mechanisms", ", ".join(f"`{m}`" for m in e.mechanisms)))
    if e.tags:
        rows.append(("Tags", ", ".join(f"`{t}`" for t in e.tags)))
    for label, value in rows:
        out.append(f"- **{label}:** {value}")
    for gate in e.gates:
        out.append(f"- **Acceptance {gate.name}:** {gate.state} "
                   f"({'required' if gate.required else 'optional'})"
                   + (" — " + "; ".join(gate.evidence) if gate.evidence else ""))
    for label, value in (("Hypothesis", e.hypothesis), ("Prediction", e.prediction),
                         ("Bar", e.bar), ("Why filed", e.why_filed)):
        if value:
            out.append(f"- **{label}:** {value}")
    if e.null_checks:
        out.append("- **Null checks:** " + "; ".join(e.null_checks))
    for label, values in (("Sources", e.sources), ("Supersedes", e.supersedes),
                          ("Related", e.related)):
        if values:
            out.append(f"- **{label}:** " + ", ".join(values))
    if e.body:
        out += ["", e.body.rstrip()]
    out.append("")
    return out


def board(config, entries, runs, target=None, best=None, skipped_runs=0,
          best_metrics=None) -> str:
    """One screen answering what is currently true.

    Modelled on the source harness's `bin/board`, which existed because a cold
    session had to read ~8,000 lines of append-only prose to find out who was
    working on what (H108). Here it is a projection of records, so it cannot
    disagree with them.
    """
    goal = config.goal
    out = [f"# {config.name} — board", ""]

    out.append(f"## Goal: {goal.id}")
    out.append(f"objective  {goal.objective}  ({goal.direction})")
    if goal.derived:
        out.append("derived    " + ", ".join(f"{k} = {v}" for k, v in goal.derived.items()))
    out.append(f"target     {_fmt(target) if target is not None else '(not probed)'}"
               + ("  [moving]" if goal.target.moving else ""))
    if best is not None and target:
        value, entry_id = best
        distance = goal.distance_to(value, target)
        # GOAL MET is the stop decision's own answer: a stop_when clause is
        # the goal's definition of "met" (qsb requires +1% over a moving
        # target), so the board must not derive a second, looser one from
        # raw distance.
        met = goal.is_met(best_metrics or {}, target)
        out.append(f"best       {_fmt(value)}  ({entry_id})   "
                   f"distance {distance:+.2%}"
                   + ("  ** GOAL MET **" if met else ""))
    else:
        out.append("best       (no valid measurement yet)")
    out.append("")

    for track in config.tracks.values():
        mine = [e for e in entries if track.is_id(e.id)]
        machine = track.machine
        counts = {}
        for e in mine:
            counts[e.status] = counts.get(e.status, 0) + 1
        out.append(f"## {track.title} — {len(mine)} entries read")
        out.append("  " + ("  ".join(f"{k}:{v}" for k, v in sorted(counts.items()))
                           or "(none)"))
        readiness = {}
        for e in mine:
            value = e.gate_readiness(machine.required_gates)
            readiness[value] = readiness.get(value, 0) + 1
        out.append("  readiness: " + ("  ".join(
            f"{key}:{value}" for key, value in sorted(readiness.items())) or "(none)"))
        held = [e for e in mine if e.claim and not machine.status(e.status).terminal]
        out.append(f"  live claims: {len(held)}")
        for e in held:
            out.append(f"    {e.id}  {e.claim.session}  since {e.claim.at[:16]} "
                       f" [{e.gate_readiness(machine.required_gates)}]")
        queued = sorted((e for e in mine if e.status == machine.initial),
                        key=lambda e: -getattr(e, "_score", 0))
        out.append(f"  queued heads ({len(queued)} queued):")
        for e in queued[:3]:
            out.append(f"    {e.id}  {e.title[:80]} "
                       f" [{e.gate_readiness(machine.required_gates)}]")
        if not queued:
            out.append("    (none — the queue is empty, not merely all held)")
        out.append("")

    ok = [r for r in runs if r.status == "ok"]
    out.append(f"## Measurements — {len(runs)} rows read, {len(ok)} valid"
               + (f", {skipped_runs} foreign rows skipped (pre-adoption schema)"
                  if skipped_runs else ""))
    for r in sorted(runs, key=lambda r: r.started)[-3:]:
        metrics = " ".join(f"{k}={_fmt(v)}" for k, v in sorted(r.metrics.items()))
        out.append(f"  {r.id}  {r.status:8} {r.entry or '—':6} {metrics}")
    if not runs:
        out.append("  (no measurements recorded)")
    out.append("")

    # The skills line is here so the dominant mode -- domains driving work by
    # hand through claim/close -- can see what the distil mechanism has left
    # to do without running the coordinator. `outstanding` is the same pair
    # the `ar skill distil --dry-run` prints; an absent skills directory reads
    # as zero (the config.py Skills contract), so the line prints even on a
    # domain that has never distilled anything.
    found, _problems = skills_mod.read_all(config)
    skills_state = skills_mod.outstanding(config, entries)
    out.append(f"## Skills — {len(found)} skill(s) read, "
               f"{len(skills_state['stale'])} stale, "
               f"{len(skills_state['undistilled'])} undistilled")
    return "\n".join(out) + "\n"


# -- the graph view -------------------------------------------------------

#: Fill per status name, for the ones the default machines declare. A status
#: outside this map takes a neutral fill, tinted darker when terminal, so a
#: domain's custom machine still renders legibly without this file knowing it.
_MERMAID_FILL = {
    "queued": "#e8e8e8",
    "blocked": "#ffe3b3",
    "in-progress": "#cfe2ff",
    "confirmed": "#d3f0d3",
    "fixed": "#d3f0d3",
    "refuted": "#f8d3d3",
    "superseded": "#eadcf5",
    "wontfix": "#e8e8e8",
}


def _mermaid_text(text: str, limit: int = 80) -> str:
    """One line, quote-safe: a node label is double-quoted, so a `"` or a
    line break in a title would break out of it."""
    text = " ".join(str(text).split()).replace('"', "'").replace("`", "'")
    return text[:limit] + ("…" if len(text) > limit else "")


#: Below this many edge-less entries, every node sits in the main flow: a
#: short row of loose nodes reads fine, and subgraph chrome is noise. Above
#: it, dagre lays the loose nodes in one horizontal line (the QSB corpus:
#: 256 unlinked entries -> a 157,000px-wide, 137px-tall diagram), so they
#: are bucketed into one status-labelled subgraph per status, chained
#: vertically with invisible links (`~~~`, mermaid >= 9.4).
BUCKET_MIN = 12


def graph_view(track, entries, circles=False, direction="TD") -> str:
    """The track's hypothesis tree as a mermaid flowchart: the graph view.

    Obsidian normalised two things: notes that link to each other, and a
    picture drawn from those links rather than maintained beside them. The
    links already exist in the records -- a branch's `parent`, an entry it
    `supersedes`, the entries it is `related` to -- so the picture is
    generated like every other view: records in, markdown out, and a hand
    edit is a validate failure. Agents draw nothing by hand: `ar entry graph`
    prints this same markdown, and a diagram of their own (a mechanism
    sketch, a decision tree) is a ```mermaid fence in an entry body or a
    memo, which renders but is never parsed back.

    Edges only join entries on this track: a branch cannot cross tracks
    (tree.py), and a view that silently reached across would make one track's
    rendering depend on another's records. Ordering is fully sorted, so the
    same records always render byte-identical output.

    Entries that carry no edge the picture can draw are not dropped: a graph
    that silently omitted most of the record would lie by omission. Past
    BUCKET_MIN they are grouped into status subgraphs instead of the main
    flow, because the flowchart engine cannot wrap loose nodes (see
    BUCKET_MIN). A filed parent moves an entry out of its bucket on the next
    render, which is the whole point of drawing from the records.

    `circles` shrinks every node to an id-bearing circle -- the Obsidian
    graph look, used by the HTML snapshot where the hover tooltip carries
    the full title and summary. The default keeps the title in the label,
    because the markdown surfaces (Obsidian, GitHub) have no hover payload
    to fall back on.

    `direction` is the mermaid flowchart orientation ("TD" default; the
    HTML snapshot passes "LR", reading lineage left to right). Bucket
    subgraphs always stack their members top-to-bottom regardless, so a
    wide corpus stays pannable in either orientation.
    """
    machine = track.machine
    mine = sorted((e for e in entries if track.is_id(e.id)), key=lambda e: e.id)
    ids = {e.id for e in mine}

    class_of, fills = {}, {}
    for e in mine:
        if e.status not in class_of:
            class_of[e.status] = "s_" + re.sub(r"\W", "_", e.status)
            fills[e.status] = _MERMAID_FILL.get(
                e.status,
                "#e0d5eb" if machine.status(e.status).terminal else "#eeeeee")

    def node(e, indent="    "):
        if circles:
            return f"{indent}{e.id}(({e.id})):::{class_of[e.status]}"
        return (f'{indent}{e.id}["{e.id} — {_mermaid_text(e.title)}"]'
                f":::{class_of[e.status]}")

    edge_pairs = []
    for e in mine:
        if e.parent and e.parent in ids:
            edge_pairs.append(
                (e.parent, e.id, f' -->|"{e.kind}"| ' if e.kind else " --> "))
    for e in mine:
        for old in sorted(e.supersedes):
            if old in ids:
                edge_pairs.append((old, e.id, ' ==>|"superseded by"| '))
    drawn: set[tuple[str, str]] = set()
    for e in mine:
        for rel in sorted(e.related):
            pair = tuple(sorted((e.id, rel)))
            if rel in ids and pair not in drawn:
                edge_pairs.append((pair[0], pair[1], " <-.->|related| "))
                drawn.add(pair)
    edges = [f"    {a}{label}{b}" for a, b, label in edge_pairs]
    # Every id an edge touches is in the main flow. Both endpoints count: a
    # superseded entry or a one-directional `related` target carries a drawn
    # edge its own record does not mention, and classifying it loose would
    # draw the node twice (main flow + bucket).
    linked = {a for a, _, _ in edge_pairs} | {b for _, b, _ in edge_pairs}
    isolated = [e for e in mine if e.id not in linked]

    out = [BANNER, f"# {track.title} — Hypothesis Graph", "",
           "```mermaid", f"flowchart {direction}"]
    if not mine:
        out.append("    %% no entries yet")
    elif len(isolated) >= BUCKET_MIN:
        out += [node(e) for e in mine if e.id in linked]
        out += edges
        for status in sorted({e.status for e in isolated}):
            members = [e for e in isolated if e.status == status]
            out.append(f'    subgraph {class_of[status]}_bucket'
                       f'["{status} — {len(members)} unlinked"]')
            out.append(f"        direction {direction}")
            prev = None
            for e in members:
                out.append(node(e, indent="        "))
                if prev:
                    out.append(f"        {prev} ~~~ {e.id}")
                prev = e.id
            out.append("    end")
    else:
        out += [node(e) for e in mine]
        out += edges
    for status in sorted(class_of):
        out.append(f"    classDef {class_of[status]} "
                   f"fill:{fills[status]},stroke:#555,color:#111")
    out += ["```", ""]
    return "\n".join(out) + "\n"


def graph_html(tracks, entries) -> str:
    """A standalone HTML snapshot of the graph views, hover-annotated.

    `ar entry graph --html PATH` writes this. The mermaid fence only carries
    the truncated label, so the page embeds one JSON record per entry -- full
    title, status, and the summary (a closure's `result.summary`, or the
    hypothesis claim for an entry that has no verdict yet) -- and hovering a
    node shows it. A snapshot, not a view: nothing checks it against the
    records, which is also why it is written only when asked for.

    The JSON is embedded with `</` escaped, so a summary containing a closing
    script tag cannot terminate the block early.
    """
    info, sections = {}, []
    for track in tracks:
        view = graph_view(track, entries, circles=True, direction="LR")
        fence = view.split("```mermaid\n", 1)[1].rsplit("```", 1)[0]
        title = html.escape(track.title, quote=False)
        sections.append(f"<h2>{title}</h2>\n"
                        f'<pre class="mermaid">\n{fence}</pre>')
        for e in entries:
            if not track.is_id(e.id) or e.id in info:
                continue
            summary = (e.result.summary if e.result is not None else "") \
                or e.hypothesis
            info[e.id] = {"title": e.title, "status": e.status,
                          "summary": summary}
    payload = json.dumps(info, sort_keys=True).replace("</", "<\\/")
    return _GRAPH_HTML_PAGE.replace("/*SECTIONS*/",
                                    "\n".join(sections)).replace(
        "/*INFO*/", payload)


_GRAPH_HTML_PAGE = """<!doctype html>
<html><head><meta charset="utf-8">
<title>Hypothesis Graph</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
  body { margin: 0; font-family: -apple-system, sans-serif; }
  header { position: sticky; top: 0; background: #fff; padding: 8px 16px;
           border-bottom: 1px solid #ddd; font-size: 13px; color: #555; z-index: 1; }
  svg { max-width: none !important; }
  /* natural size: scrollbars pan, browser zoom (Cmd+/-) rescales */
  #tip { display: none; position: fixed; max-width: 480px; background: #222;
         color: #eee; font-size: 13px; line-height: 1.4; padding: 10px 12px;
         border-radius: 6px; pointer-events: none; z-index: 2; }
  #tip .t { font-weight: 600; margin-bottom: 2px; }
  #tip .s { color: #9ec; font-size: 11px; text-transform: uppercase;
            letter-spacing: .04em; margin-bottom: 6px; }
  #tip .m { white-space: pre-wrap; }
</style></head>
<body>
<header>Hypothesis Graph · generated from state/entries/ by <code>ar render</code>;
this file is a snapshot -- re-run <code>ar entry graph --html</code> after the record
moves. Hover a node for the full title and summary. Scroll to pan; Cmd+/- to zoom.</header>
<div id="tip"></div>
/*SECTIONS*/
<script>const INFO = /*INFO*/;
// Layout density and the scale the page opens at. nodeSpacing/rankSpacing are
// mermaid's gaps (defaults 50/50); ZOOM shrinks the rendered SVG so the page
// opens zoomed out over more of the graph -- Cmd+/- rescales on top of it.
const ZOOM = 0.6;
mermaid.initialize({ startOnLoad: true,
                     flowchart: { nodeSpacing: 12, rankSpacing: 28 } });
mermaid.run({ querySelector: '.mermaid' }).then(() => {
  document.querySelectorAll('svg').forEach(svg => {
    const b = svg.getBBox();
    svg.style.maxWidth = 'none';
    svg.style.width = Math.round(b.width * ZOOM) + 'px';
    svg.style.height = 'auto';
  });
  const tip = document.getElementById('tip');
  document.querySelectorAll('svg .node').forEach(n => {
    // The node id is the record's key: circle labels read "<ID>", rectangle
    // labels "<ID> — <title>"; either matches at the start.
    const m = n.textContent.match(/^\\s*([A-Za-z]+\\d+)/);
    if (!m || !INFO[m[1]]) return;
    n.style.cursor = 'help';
    n.addEventListener('mousemove', ev => {
      const d = INFO[m[1]];
      tip.textContent = '';
      const t = document.createElement('div'); t.className = 't';
      t.textContent = m[1] + ' — ' + d.title;
      const s = document.createElement('div'); s.className = 's';
      s.textContent = d.status;
      const body = document.createElement('div'); body.className = 'm';
      body.textContent = d.summary || '(no hypothesis recorded)';
      tip.append(t, s, body);
      tip.style.display = 'block';
      const pad = 14, w = tip.offsetWidth, h = tip.offsetHeight;
      tip.style.left = Math.min(ev.clientX + pad,
                                window.innerWidth - w - pad) + 'px';
      tip.style.top = Math.min(ev.clientY + pad,
                               window.innerHeight - h - pad) + 'px';
    });
    n.addEventListener('mouseleave', () => { tip.style.display = 'none'; });
  });
}).catch(e => { document.body.textContent = 'mermaid failed: ' + e.message; });
</script>
</body></html>
"""


# -- writing and checking views ------------------------------------------

def write_views(config, entries) -> list[pathlib.Path]:
    written = []
    for track in config.tracks.values():
        path = config.paths.root / track.view
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(queue_view(track, entries))
        written.append(path)
        if track.graph_view:
            path = config.paths.root / track.graph_view
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(graph_view(track, entries))
            written.append(path)
    if _memos_pending(config):
        path = config.paths.memos / MEMOS_INDEX
        path.write_text(memos_index_view(config, entries))
        written.append(path)
    return written


def check_views(config, entries) -> list[str]:
    """Views that differ from what the records render.

    This is invariant 1 made enforceable: a generated document that someone
    hand-edited is a build failure, not a divergence nobody notices.
    """
    problems = []
    for track in config.tracks.values():
        path = config.paths.root / track.view
        expected = queue_view(track, entries)
        if not path.exists():
            # Distinguish "you have not adopted this domain yet" from "you
            # forgot to re-render". Both leave no file, and pointing the first
            # case at `ar render` sends the reader the wrong way: rendering an
            # empty store writes an empty queue and looks like it worked.
            mine = [e for e in entries if track.is_id(e.id)]
            if not mine and track.migrate_from:
                problems.append(
                    f"{track.view} does not exist and this track holds no "
                    f"records. Its source document is {track.migrate_from!r}: "
                    f"run `ar migrate` first, then `ar render`.")
            else:
                problems.append(
                    f"{track.view} has never been rendered (`ar render`)")
        elif path.read_text() != expected:
            problems.append(
                f"{track.view} differs from what the records render. It is a "
                f"generated view: edit the entry record and re-run `ar render`.")
        if track.graph_view:
            path = config.paths.root / track.graph_view
            expected = graph_view(track, entries)
            if not path.exists():
                problems.append(
                    f"{track.graph_view} has never been rendered (`ar render`)")
            elif path.read_text() != expected:
                problems.append(
                    f"{track.graph_view} differs from what the records render. "
                    f"It is a generated view: edit the entry record and re-run "
                    f"`ar render`.")
    if _memos_pending(config):
        path = config.paths.memos / MEMOS_INDEX
        # Message names the file relative to the domain root, matching how the
        # track problems above name their views.
        name = str(path.relative_to(config.paths.root))
        expected = memos_index_view(config, entries)
        if not path.exists():
            problems.append(f"{name} has never been rendered (`ar render`)")
        elif path.read_text() != expected:
            problems.append(
                f"{name} differs from what the records render. It is a "
                f"generated view: edit the entry record and re-run `ar render`.")
    return problems
